name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Verify documentation sync
      run: |
        # Check if all documented features have tests
        swift test --filter "MacAITextImproverTests.WritingStyleTests/testAllDocumentedStylesExist"
    
    - name: Build for ${{ matrix.arch }}
      run: |
        arch -${{ matrix.arch }} swift build -c release
    
    - name: Run unit tests
      run: |
        arch -${{ matrix.arch }} swift test --filter "MacAITextImproverTests.WritingStyleTests"
    
    - name: Run integration tests
      run: |
        arch -${{ matrix.arch }} swift test --filter "MacAITextImproverTests.Integration"
    
    - name: Run UI tests
      run: |
        arch -${{ matrix.arch }} swift test --filter "MacAITextImproverTests.UI"
    
    - name: Generate test coverage report
      run: |
        xcrun llvm-cov export \
          .build/${{ matrix.arch }}-apple-macosx/debug/MacAITextImproverPackageTests.xctest/Contents/MacOS/MacAITextImproverPackageTests \
          -instr-profile=.build/debug/codecov/default.profdata \
          -format=lcov > coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        flags: ${{ matrix.arch }}
        fail_ci_if_error: true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacAITextImprover-${{ matrix.arch }}
        path: .build/release/MacAITextImprover
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.arch }}
        path: |
          .build/debug/codecov/
          coverage.lcov