name: Build

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    - name: Build App
      run: |
        # Clean any previous builds
        rm -rf .build
        rm -rf MacAITextImprover.app
        
        # Build the project
        swift build -c release
        
        # Create app bundle
        APP_NAME="MacAITextImprover"
        APP_DIR="$APP_NAME.app"
        CONTENTS_DIR="$APP_DIR/Contents"
        MACOS_DIR="$CONTENTS_DIR/MacOS"
        RESOURCES_DIR="$CONTENTS_DIR/Resources"
        
        mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
        cp ".build/release/$APP_NAME" "$MACOS_DIR/"
        cp MacAITextImprover.app/Contents/Info.plist "$CONTENTS_DIR/"
    
    - name: Create DMG
      run: |
        APP_NAME="MacAITextImprover"
        VERSION=$(git describe --tags --abbrev=0)
        DMG_NAME="$APP_NAME-${VERSION}.dmg"
        hdiutil create -volname "$APP_NAME" \
                      -srcfolder "$APP_NAME.app" \
                      -ov -format UDZO \
                      "$DMG_NAME"
    
    - name: Generate Release Notes
      id: release_notes
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "CHANGELOG_SECTION<<EOF" >> $GITHUB_ENV
        sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref_name }}
        body: ${{ env.CHANGELOG_SECTION }}
        files: MacAITextImprover-*.dmg
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}