name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            name: Intel
          - arch: arm64
            name: Apple Silicon
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    - name: Build for ${{ matrix.arch }}
      run: |
        # Clean any previous builds
        rm -rf .build
        rm -rf MacAITextImprover.app
        
        # Build the project
        arch -${{ matrix.arch }} swift build -c release
        
        # Create app bundle
        APP_NAME="MacAITextImprover"
        APP_DIR="$APP_NAME.app"
        CONTENTS_DIR="$APP_DIR/Contents"
        MACOS_DIR="$CONTENTS_DIR/MacOS"
        RESOURCES_DIR="$CONTENTS_DIR/Resources"
        
        mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
        cp ".build/release/$APP_NAME" "$MACOS_DIR/"
        cp MacAITextImprover.app/Contents/Info.plist "$CONTENTS_DIR/"
    
    - name: Create DMG
      run: |
        APP_NAME="MacAITextImprover"
        hdiutil create -volname "$APP_NAME-${{ matrix.name }}" \
                      -srcfolder "$APP_NAME.app" \
                      -ov -format UDZO \
                      "$APP_NAME-${{ matrix.name }}.dmg"
    
    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: MacAITextImprover-${{ matrix.name }}.app
        path: MacAITextImprover.app
    
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: MacAITextImprover-${{ matrix.name }}.dmg
        path: MacAITextImprover-${{ matrix.name }}.dmg