name: Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      
      - name: Build
        run: |
          swift build -c release
          mkdir -p MacAITextImprover.app/Contents/MacOS
          cp .build/release/MacAITextImprover MacAITextImprover.app/Contents/MacOS/
          chmod +x MacAITextImprover.app/Contents/MacOS/MacAITextImprover
      
      - name: Create DMG
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          DMG_NAME="MacAITextImprover-${VERSION}.dmg"
          hdiutil create -volname "MacAITextImprover" \
                        -srcfolder MacAITextImprover.app \
                        -ov -format UDZO \
                        "${DMG_NAME}"
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: MacAITextImprover-*.dmg
          draft: true 