name: Build

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    - name: Build App
      run: |
        swift build -c release
        
        APP_NAME="MacAITextImprover"
        APP_DIR="$APP_NAME.app"
        CONTENTS_DIR="$APP_DIR/Contents"
        MACOS_DIR="$CONTENTS_DIR/MacOS"
        RESOURCES_DIR="$CONTENTS_DIR/Resources"
        
        mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
        cp ".build/release/$APP_NAME" "$MACOS_DIR/"
        cp MacAITextImprover.app/Contents/Info.plist "$CONTENTS_DIR/"
        chmod +x "$MACOS_DIR/$APP_NAME"
    
    - name: Create DMG
      run: |
        APP_NAME="MacAITextImprover"
        VERSION=${GITHUB_REF#refs/tags/v}
        DMG_NAME="$APP_NAME-${VERSION}.dmg"
        
        hdiutil create -volname "$APP_NAME" \
                      -srcfolder "$APP_NAME.app" \
                      -ov -format UDZO \
                      "$DMG_NAME"
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: MacAITextImprover-*.dmg
        body_file: CHANGELOG.md
        draft: true