name: Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build Local App Bundle
        run: |
          # Run the local build script
          chmod +x build.sh
          ./build.sh
          
          # Verify the app bundle was created
          if [ ! -d "MacAITextImprover.app" ]; then
            echo "App bundle was not created"
            exit 1
          fi
      
      - name: Create DMG
        id: create_dmg
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          DMG_NAME="MacAITextImprover-${VERSION}.dmg"
          
          # Create DMG
          hdiutil create -volname "MacAITextImprover" \
                        -srcfolder MacAITextImprover.app \
                        -ov -format UDZO \
                        "${DMG_NAME}"
          
          # Create artifacts directory and move DMG
          mkdir -p artifacts
          mv "${DMG_NAME}" artifacts/
          
          # Set output for release step
          echo "dmg_path=artifacts/${DMG_NAME}" >> $GITHUB_OUTPUT
          
          # List contents for verification
          ls -la artifacts/
      
      - name: Extract Release Notes
        id: release_notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracting release notes for version ${VERSION}"
          
          # Create release notes file
          mkdir -p artifacts
          
          # Extract the specific version's notes
          echo "# Release Notes for v${VERSION}" > artifacts/release_notes.md
          echo "" >> artifacts/release_notes.md
          awk "/## \[${VERSION}\]/,/## \[/" CHANGELOG.md | grep -v "^## \[" >> artifacts/release_notes.md
          
          # Verify release notes were extracted
          if [ ! -s artifacts/release_notes.md ]; then
            echo "Error: Release notes extraction failed"
            echo "Checking CHANGELOG.md content:"
            cat CHANGELOG.md
            exit 1
          fi
          
          echo "Release notes content:"
          cat artifacts/release_notes.md
          
          echo "notes_path=artifacts/release_notes.md" >> $GITHUB_OUTPUT
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/
          if-no-files-found: error
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.create_dmg.outputs.dmg_path }}
          body_path: ${{ steps.release_notes.outputs.notes_path }}
          draft: true