name: Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Environment
      run: |
        xcodebuild -version
        swift --version
        xcrun --sdk macosx --show-sdk-path
    
    - name: Set up Swift
      run: |
        swift package resolve
    
    - name: Create test directories
      run: |
        mkdir -p .build/debug
        mkdir -p Tests/MacAITextImproverTests
    
    - name: Run Tests
      run: |
        # Build and test for both architectures
        echo "Testing Apple Silicon build..."
        swift test --enable-test-discovery --arch arm64
        
        echo "Testing Intel build..."
        swift test --enable-test-discovery --arch x86_64
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: .build/debug/
