name: Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    # Set up Swift environment
    - name: Set up Swift
      run: |
        swift --version
        swift package reset
        swift package clean
        swift package resolve
    
    # Run tests
    - name: Run tests
      run: |
        swift build
        swift test --enable-test-discovery
    
    # Upload Test Results
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .build/debug/
