name: Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
    
    - name: Set up Swift
      run: |
        swift --version
        swift package resolve
    
    - name: Create test directories
      run: |
        mkdir -p .build/debug
        mkdir -p Tests/MacAITextImproverTests
    
    - name: Run Tests
      run: |
        # Build and test
        swift build
        swift test --enable-test-discovery
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: .build/debug/
