name: Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    # Basic test setup
    - name: Set up test environment
      run: |
        mkdir -p .build/debug/MacAITextImproverPackageTests.xctest/Contents/MacOS
        defaults write com.apple.dt.XCTest HeadlessMode -bool YES
    
    # Start with just the basic tests
    - name: Run Writing Style Tests
      run: swift test --filter "MacAITextImproverTests.WritingStyleTests" --enable-test-discovery
    
    - name: Run AI Service Tests
      run: swift test --filter "MacAITextImproverTests.AIServiceTests" --enable-test-discovery
    
    # Upload Test Results
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .build/debug/
