name: Tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debug logging enabled'
        required: false
        default: false
        type: boolean

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    # Set up test environment
    - name: Set up test environment
      run: |
        # Create test directories
        mkdir -p UIBaselines
        mkdir -p .build/debug/codecov
        mkdir -p "$HOME/Library/Application Support/com.apple.TCC"
        
        # Create TCC database if it doesn't exist
        if [ ! -f "$HOME/Library/Application Support/com.apple.TCC/TCC.db" ]; then
          sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "CREATE TABLE access (service TEXT NOT NULL, client TEXT NOT NULL, client_type INTEGER NOT NULL, allowed INTEGER NOT NULL, prompt_count INTEGER NOT NULL, csreq BLOB, policy_id INTEGER, indirect_object_identifier_type INTEGER, indirect_object_identifier TEXT NOT NULL, indirect_object_code_identity BLOB, flags INTEGER NOT NULL, last_modified INTEGER NOT NULL);"
        fi
        
        # Set up permissions for Speech Recognition in tests
        sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" \
          "INSERT OR REPLACE INTO access (service,client,client_type,allowed,prompt_count,csreq,policy_id,indirect_object_identifier_type,indirect_object_identifier,indirect_object_code_identity,flags,last_modified) VALUES('kTCCServiceMicrophone','com.apple.dt.xctest',0,1,1,NULL,NULL,0,'UNUSED',NULL,0,1);"
        sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" \
          "INSERT OR REPLACE INTO access (service,client,client_type,allowed,prompt_count,csreq,policy_id,indirect_object_identifier_type,indirect_object_identifier,indirect_object_code_identity,flags,last_modified) VALUES('kTCCServiceSpeechRecognition','com.apple.dt.xctest',0,1,1,NULL,NULL,0,'UNUSED',NULL,0,1);"
        
        # Enable headless mode for tests
        defaults write com.apple.dt.xctest HeadlessMode -bool YES
        
        # Set up audio session
        sudo launchctl bootout system/com.apple.audio.coreaudiod 2>/dev/null || true
        sudo launchctl bootstrap system/com.apple.audio.coreaudiod
        
        # Wait for audio service to be ready
        sleep 5
    
    # Feature Tests
    - name: Run Writing Style Tests
      run: |
        mkdir -p .build/debug/MacAITextImproverPackageTests.xctest/Contents/MacOS
        swift test --filter "MacAITextImproverTests.WritingStyleTests" --enable-test-discovery
    
    - name: Run AI Service Tests
      run: swift test --filter "MacAITextImproverTests.AIServiceTests" --enable-test-discovery
    
    - name: Run Speech Recognition Tests
      run: |
        # Mock speech recognition authorization for tests
        defaults write com.apple.speech.recognition.AppleSpeechRecognitionServer AuthorizationStatus -int 3
        swift test --filter "MacAITextImproverTests.SpeechRecognitionTests" --enable-test-discovery
    
    - name: Run Text-to-Speech Tests
      run: swift test --filter "MacAITextImproverTests.TextToSpeechTests" --enable-test-discovery
    
    # UI Tests
    - name: Run Content View Tests
      run: |
        # Set up UI test environment
        defaults write com.apple.CoreSimulator.IndigoFramebufferServices FramebufferStatus -bool NO
        swift test --filter "MacAITextImproverTests.ContentViewTests" --enable-test-discovery
    
    - name: Run UI Consistency Tests
      run: swift test --filter "MacAITextImproverTests.UIConsistencyTests" --enable-test-discovery
    
    # Generate Coverage Report
    - name: Generate Code Coverage
      run: |
        swift test --enable-code-coverage --enable-test-discovery
        xcrun llvm-cov export -format="lcov" \
          .build/debug/MacAITextImproverPackageTests.xctest/Contents/MacOS/MacAITextImproverPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          > coverage.lcov
    
    # Upload Coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        fail_ci_if_error: true
    
    # Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          .build/debug/codecov/
          coverage.lcov
          UIBaselines/
    
    # Create Test Report
    - name: Create Test Summary
      if: always()
      run: |
        echo "# Test Results Summary" > test_summary.md
        echo "" >> test_summary.md
        echo "## Coverage Report" >> test_summary.md
        echo "\`\`\`" >> test_summary.md
        cat coverage.lcov | grep -E "^SF:|^LF:|^LH:" >> test_summary.md
        echo "\`\`\`" >> test_summary.md
        
        # Add UI test results if available
        if [ -d "UIBaselines/Reports" ]; then
          echo "" >> test_summary.md
          echo "## UI Test Results" >> test_summary.md
          cat UIBaselines/Reports/*.md >> test_summary.md
        fi
    
    # Add PR Comment
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('test_summary.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: summary
          });