name: Tests

on:
  push:
    branches: [ main, develop, feature/**, bugfix/** ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    - name: Verify Project Structure
      run: |
        # Check essential files exist
        for file in Package.swift VERSION CHANGELOG.md; do
          if [ ! -f "$file" ]; then
            echo "$file is missing"
            exit 1
          fi
        done
        
        # Check source directories exist
        for dir in Sources Tests; do
          if [ ! -d "$dir" ]; then
            echo "$dir directory is missing"
            exit 1
          fi
        done
    
    - name: Swift Package Resolution
      run: swift package resolve
    
    - name: Build Project
      run: |
        # Clean and build
        rm -rf .build
        swift build -v
    
    - name: Run Tests
      run: |
        # Run tests with coverage
        swift test --enable-code-coverage --enable-test-discovery --verbose
    
    - name: Generate Coverage Report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/MacAITextImproverPackageTests.xctest/Contents/MacOS/MacAITextImproverPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage.lcov
        fail_ci_if_error: true
    
    - name: Verify Test Results
      run: |
        # Check if any tests failed
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
    
    - name: Build App Bundle
      run: |
        # Create app bundle to verify full build process
        APP_NAME="MacAITextImprover"
        APP_DIR="$APP_NAME.app"
        CONTENTS_DIR="$APP_DIR/Contents"
        MACOS_DIR="$CONTENTS_DIR/MacOS"
        RESOURCES_DIR="$CONTENTS_DIR/Resources"
        
        mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"
        cp ".build/debug/$APP_NAME" "$MACOS_DIR/"
        cp MacAITextImprover.app/Contents/Info.plist "$CONTENTS_DIR/"
    
    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          .build/debug/codecov/
          coverage.lcov
